apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-application
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx-application
  replicas: {{ .Values.app.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx-application
    spec:
      containers:
      - name: {{ .Release.Name }}-nginx-application
        image: {{ .Values.app.image.name }}:{{ .Values.app.image.tag }}
        ports:
        - containerPort: 8080
