apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  namespace: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-nginx-service
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

